### ISSUE TITLE
[Events] Join Event button is displayed for unauthorized user on the Event preview card  

### ISSUE THREAD

**Issue by Githubenko** [ita-social-projects/GreenCity#4579]
Environment: Mac OS High Sierra: Version 10.13.6, Google Chrome: Version 105.0.5195.102 
Reproducible: always
Build found: 8.09.2022

Description:
This test case verifies that Non-authorized is not able to view the Join Event button on the Event preview card.

Preconditions:
 Go to "Events page" https://www.testgreencity.ga/GreenCityClient/#/events, do not sign in

Steps to reproduce:
1. View "Event preview card"

Actual result:
"Join Event" button is displayed on the "Event preview card"

Expected result:
"Join Event" button is not displayed on the "Event preview card"

User story and test case links
[User story] https://github.com/ita-social-projects/GreenCity/issues/3374
[Test case] https://jira.softserve.academy/browse/GC-3553

**Comment by NataliaVirt** [comment]
Fixed
![image](https://user-images.githubusercontent.com/112310945/198135586-483c7978-2a4d-4e7a-8e98-ff13da12e6a5.png)

**Comment by YelyzavetaSheptytska** [comment]
[New Recording - 11_17_2022, 11_51_52 AM.webm](https://user-images.githubusercontent.com/112197311/202427770-070fbf7b-af48-420a-8a0b-1ba98e2f648a.webm)

"Join Event" button is still appear for no-authorized user on the Event preview card after pressing the "Rate organizer" button as no-authorized user

**Comment by SokhaTaras** [comment]
![image](https://user-images.githubusercontent.com/86615598/216299691-290ec25d-db3a-4eca-8c5e-ed0a5d25021b.png)
