### ISSUE TITLE
[UBS Order Form][Step 0.1.] Clicking outside of the pop-up doesn't close it

### ISSUE THREAD

**Issue by NeonilaH** [ita-social-projects/GreenCity#5266]
**Environment:** Windows 11 Home, Google Chrome 109.0.5414.122.
**Reproducible:** always.

**Description**
According to the acceptance criteria of the user story #3033, clicking outside of the pop-up should close it and redirect the user to the previous page:
>8. By clicking on the button “Назад”, on “X” (close), or outside of the pop-up, the pop-up should close, and the user shall be redirected to the page, from which the popup was entered. The button “Назад” is always active.

**Preconditions**
The user is authorized on the website.

**Steps to reproduce**
1. Open the https://www.greencity.social/#/ubs URL.
2. Click on the 'Замовити Кур’єра' button.
3. Click outside of the pop-up on the background page.
4. Pay attention to the pop-up.

**Actual result**
1. The pop-up is not closed. 
2. The user is not redirected to https://www.greencity.social/#/ubs.

**Expected result**
1. The pop-up is closed. 
2. The user is redirected to https://www.greencity.social/#/ubs.

**User story and test case links**
User-story #3033
[Test case WR50QC-571 in Jira](https://jira.softserve.academy/browse/WR50QC-571)

**Comment by katia9261** [comment]
Bug is fixed
https://github.com/ita-social-projects/GreenCity/assets/101433204/93f7efef-1d79-4066-aec7-e428e3aadfa3

**Comment by NeonilaH** [comment]
@katia9261  **The bug is not fixed when the pop-up is opened on UBS main page.** 
The bug is fixed when the pop-up is opened on the UBS Order page.

https://github.com/ita-social-projects/GreenCity/assets/106426661/de1b047c-e169-4a74-be1f-f32483e13abd

**Comment by Vadym840217** [comment]
To reproduce this bug User needs to have no orders in 'User cabinet', then pop-up window 'first choose the location' could appear on UBS main page after clicking on 'order' button
![Pop-up_bug](https://github.com/ita-social-projects/GreenCity/assets/130633728/66b6581a-5502-420d-8fe6-9d53b806d9c8)
![Pop-up_bug_1](https://github.com/ita-social-projects/GreenCity/assets/130633728/1872c662-b63e-42ab-ac7c-e0ac893ae4ab)
