### ISSUE TITLE
[Delete draft order] Draft order is not deleted from Client Cabinet — Status 500 on delete

### ISSUE THREAD

**Issue by HorlovaSofiia** [ita-social-projects/GreenCity#9142]
**Environment:** Windows 10, Firefox 142.0.1
**Reproducible:** always.

**Preconditions**
1. Log in as a user
2. User has at least one saved draft order in the Client Cabinet.

**Steps to reproduce**
1. Navigate to Client Cabinet → Draft orders.
2. Locate an existing draft order
3. Click Delete
4. Refresh the page
5. Observe the response in Swagger and browser DevTools.
**Actual result**
When attempting to delete a draft order from the Client Cabinet, the system responds with an HTTP 500 Internal Server Error. The draft order remains in the Cabinet and is not removed. The error is visible both in the Swagger (client-controller [/ubs/client/delete-order/{id}) and in the browser’s network inspector. Server logs indicate a failure or exception during the deletion process.

<img width="1194" height="1028" alt="Image" src="https://github.com/user-attachments/assets/f8e31c8e-0f72-4606-a003-8efd7181c61e" />

<img width="2556" height="336" alt="Image" src="https://github.com/user-attachments/assets/c91b2804-4731-47ec-8d19-362a7e9143c5" />

<img width="2560" height="345" alt="Image" src="https://github.com/user-attachments/assets/7562975b-ac11-45d5-9560-528a0a24aac2" />

**Expected result**
The draft order should be successfully deleted from the Client Cabinet.

**User story and test case links**
 User story #9009

**Comment by RostyslavZadyraichuk** [comment]
Not reproducible. Looks like it was fixed.

<img width="571" height="145" alt="Image" src="https://github.com/user-attachments/assets/e1321b70-813f-44e7-8387-e5604bd38535" />

**Comment by HorlovaSofiia** [comment]
@RostyslavZadyraichuk The bug is still reproducible for two QC. Try refreshing the page after canceling the draft order 

https://github.com/user-attachments/assets/f17befe3-5684-4479-83be-5a73e87246c9
